-- =====================================================================
-- 무료 포인트 시스템 - 스키마 (H2 2.x / MySQL 호환)
-- 설계 원칙
--   1) 거래 이력(point_transaction)과 잔액 상태(point_lot)를 분리한다.
--   2) 잔액을 보유하는 테이블은 point_lot 하나뿐이다. (단일 진실 공급원)
--      잔액 = ACTIVE 이고 만료되지 않은 Lot 의 remaining_amount 합계. 캐시하지 않는다.
--   3) 모든 금액은 1원 단위 정수(BIGINT)로 관리한다. 음수를 허용하지 않는다.
--   4) 모든 잔액 변경은 point_account 행 비관적 락 하위에서만 수행한다.
--   5) 만료는 상태로 저장하지 않고 expires_at 과 현재 시각으로 판정한다. (만료 배치 없음)
--   6) 물리 FK 는 두지 않는다. 테이블 간 관계는 각 테이블 주석의 "논리 FK" 로 명시하고
--      참조 무결성은 애플리케이션에서 보장한다. 금액 정합성은 CHECK / UNIQUE 제약으로 지킨다.
-- =====================================================================

DROP TABLE IF EXISTS point_use_cancel_detail;
DROP TABLE IF EXISTS point_use_detail;
DROP TABLE IF EXISTS point_lot;
DROP TABLE IF EXISTS point_policy;
DROP TABLE IF EXISTS point_transaction;
DROP TABLE IF EXISTS point_account;


-- 1. point_account : 사용자별 포인트 계정
--    - 동시성 제어의 단일 진입점 (SELECT ... FOR UPDATE 대상 행)
--    - 적립(INSERT)까지 직렬화해야 보유 한도 검사가 안전하므로 Lot 이 아닌 이 행을 잠근다.
CREATE TABLE point_account (
    user_id     BIGINT      NOT NULL,
    created_at  TIMESTAMP   NOT NULL,
    updated_at  TIMESTAMP   NOT NULL,
    PRIMARY KEY (user_id)
);


-- 2. point_transaction : 포인트 거래 원장
--    - type       : EARN / EARN_CANCEL / USE / USE_CANCEL
--                   사용취소 재적립(명세 예시의 E)도 EARN 이며, point_lot.origin_type 으로 구분한다.
--    - request_id : 클라이언트 요청 멱등 키. 재적립 EARN 은 시스템 생성이므로 NULL.
--    - 명세 예시의 pointKey(A,B,C,D,E)가 곧 이 테이블의 point_key
--    논리 FK
--    - user_id                -> point_account.user_id
--    - related_transaction_id -> point_transaction.id (적립취소 -> 원 적립, 사용취소 -> 원 사용)
CREATE TABLE point_transaction (
    id                      BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    point_key               VARCHAR(26)  NOT NULL,
    user_id                 BIGINT       NOT NULL,
    type                    VARCHAR(20)  NOT NULL,
    amount                  BIGINT       NOT NULL,
    canceled_amount         BIGINT       NOT NULL DEFAULT 0,
    order_no                VARCHAR(50)  NULL,
    related_transaction_id  BIGINT       NULL,
    request_id              VARCHAR(64)  NULL,
    granted_by              VARCHAR(50)  NULL,
    memo                    VARCHAR(200) NULL,
    created_at              TIMESTAMP    NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_tx_point_key  UNIQUE (point_key),
    CONSTRAINT uk_tx_request_id UNIQUE (request_id),
    CONSTRAINT ck_tx_amount     CHECK (amount > 0),
    CONSTRAINT ck_tx_canceled   CHECK (canceled_amount >= 0 AND canceled_amount <= amount)
);
CREATE INDEX idx_tx_user_created ON point_transaction (user_id, created_at DESC);
CREATE INDEX idx_tx_order_no     ON point_transaction (order_no);
CREATE INDEX idx_tx_related      ON point_transaction (related_transaction_id);


-- 3. point_lot : 적립 단위(Lot). 잔액을 보유하는 유일한 테이블
--    - source      : 사용 우선순위 판정 축 (수기지급 우선). 재적립 시 승계된다.
--    - origin_type : 발생 경위 축 (일반 적립 / 사용취소 재적립). 승계하지 않는다.
--    - status      : ACTIVE / CANCELED(적립취소). 만료 여부는 expires_at 으로 판정한다.
--    논리 FK
--    - transaction_id -> point_transaction.id (해당 Lot 을 만든 EARN 거래)
--    - user_id        -> point_account.user_id
CREATE TABLE point_lot (
    id                    BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    transaction_id        BIGINT      NOT NULL,
    user_id               BIGINT      NOT NULL,
    original_amount       BIGINT      NOT NULL,
    remaining_amount      BIGINT      NOT NULL,
    source                VARCHAR(20) NOT NULL,
    use_priority          SMALLINT    NOT NULL,
    origin_type           VARCHAR(20) NOT NULL,
    expires_at            TIMESTAMP   NOT NULL,
    status                VARCHAR(20) NOT NULL,
    created_at            TIMESTAMP   NOT NULL,
    updated_at            TIMESTAMP   NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_lot_transaction UNIQUE (transaction_id),
    CONSTRAINT ck_lot_remaining   CHECK (remaining_amount >= 0 AND remaining_amount <= original_amount),
    CONSTRAINT ck_lot_original    CHECK (original_amount > 0)
);
-- 사용 우선순위 조회 전용: 수기지급 우선 -> 만료임박 순 -> 적립순
CREATE INDEX idx_lot_use_order ON point_lot (user_id, status, use_priority, expires_at, id);


-- 4. point_use_detail : 사용 상세 (요건 3-1-3 "1원 단위 추적"의 실체)
--    - seq : 사용 시 적용된 우선순위 순번. 사용취소 복원 순서의 기준이 된다.
--    논리 FK
--    - use_transaction_id -> point_transaction.id (USE 거래)
--    - lot_id             -> point_lot.id
CREATE TABLE point_use_detail (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    use_transaction_id  BIGINT      NOT NULL,
    lot_id              BIGINT      NOT NULL,
    order_no            VARCHAR(50) NOT NULL,
    amount              BIGINT      NOT NULL,
    canceled_amount     BIGINT      NOT NULL DEFAULT 0,
    seq                 INT         NOT NULL,
    created_at          TIMESTAMP   NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ck_ud_amount      CHECK (amount > 0),
    CONSTRAINT ck_ud_canceled    CHECK (canceled_amount >= 0 AND canceled_amount <= amount)
);
CREATE INDEX idx_ud_transaction ON point_use_detail (use_transaction_id, seq);
CREATE INDEX idx_ud_lot         ON point_use_detail (lot_id);
CREATE INDEX idx_ud_order_no    ON point_use_detail (order_no);


-- 5. point_use_cancel_detail : 사용취소 상세 (감사 추적)
--    - restore_type 으로 "원 Lot 복원" / "만료로 인한 신규 재적립"을 구분
--    - 원 Lot 복원 대상은 point_use_detail.lot_id 이므로 따로 저장하지 않는다.
--    - reissued_lot_id : 신규 재적립인 경우에만 채워진다.
--    논리 FK
--    - cancel_transaction_id -> point_transaction.id (USE_CANCEL 거래)
--    - use_detail_id         -> point_use_detail.id
--    - reissued_lot_id       -> point_lot.id
CREATE TABLE point_use_cancel_detail (
    id                     BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    cancel_transaction_id  BIGINT      NOT NULL,
    use_detail_id          BIGINT      NOT NULL,
    amount                 BIGINT      NOT NULL,
    restore_type           VARCHAR(20) NOT NULL,
    reissued_lot_id        BIGINT      NULL,
    created_at             TIMESTAMP   NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ck_ucd_amount      CHECK (amount > 0)
);
CREATE INDEX idx_ucd_transaction ON point_use_cancel_detail (cancel_transaction_id);
CREATE INDEX idx_ucd_use_detail  ON point_use_cancel_detail (use_detail_id);


-- 6. point_policy : 포인트 정책 (요건 3-1-1 / 3-1-2 "하드코딩 금지")
--    - 만료 기간은 ISO-8601 Period 문자열로 관리한다.
--      "최대 5년 미만"을 일수(1825/1826) 근사 없이 정확히 표현하기 위함.
--    논리 FK
--    - user_id -> point_account.user_id (scope = USER 인 경우)
CREATE TABLE point_policy (
    id                     BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    scope                  VARCHAR(10) NOT NULL,
    user_id                BIGINT      NULL,
    min_earn_amount        BIGINT      NOT NULL DEFAULT 1,
    max_earn_amount        BIGINT      NOT NULL DEFAULT 100000,
    max_hold_amount        BIGINT      NOT NULL DEFAULT 1000000,
    min_expire_period      VARCHAR(10) NOT NULL DEFAULT 'P1D',
    max_expire_period      VARCHAR(10) NOT NULL DEFAULT 'P5Y',
    default_expire_period  VARCHAR(10) NOT NULL DEFAULT 'P365D',
    effective_from         TIMESTAMP   NOT NULL,
    effective_to           TIMESTAMP   NULL,
    created_at             TIMESTAMP   NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ck_policy_earn    CHECK (min_earn_amount >= 1 AND max_earn_amount >= min_earn_amount)
);
CREATE INDEX idx_policy_lookup ON point_policy (scope, user_id, effective_from);
